### Listar todos os usuários
GET http://localhost:3000/api/agendamento/users


### Buscar usuário por ID
GET http://localhost:3000/api/agendamento/users/686af7c34ab0bd30667ba688


### Cadastrar novo usuário
POST http://localhost:3000/api/agendamento/users
Content-Type: application/json

{
  "name": "Nome do Usuário",
  "email": "usuario@example.com",
  "password": "senha123",
  "role": "DENTISTA"
}


### Atualizar usuário
PUT http://localhost:3000/api/agendamento/users/686af7c34ab0bd30667ba688
Content-Type: application/json

{
  "name": "Nome Atualizado",
  "password": "novaSenha123"
}


### Desativar usuário
DELETE http://localhost:3000/api/agendamento/users/686af7c34ab0bd30667ba688


### Reativar usuário
PUT http://localhost:3000/api/agendamento/users/reactivate/686af7c34ab0bd30667ba688
